# Generated by Django 4.2.7 on 2026-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к картинке вопроса'),
        ),
    ]
