# Generated by Django 4.2.7 on 2026-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamequestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='emotion_change',
            field=models.IntegerField(default=0, verbose_name='Изменение эмоционального состояния'),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_change',
            field=models.IntegerField(default=0, verbose_name='Изменение времени'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='emotion_score',
            field=models.IntegerField(default=50, verbose_name='Эмоциональное состояние'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_score',
            field=models.IntegerField(default=50, verbose_name='Время'),
        ),
    ]
