# Generated by Django 4.2.11 on 2026-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_answer_emotion_change_answer_time_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Первый вопрос'),
            preserve_default=False,
        ),
    ]
