# Generated by Django 4.2.7 on 2026-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamequestion_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Первый вопрос'),
        ),
    ]
