# Generated by Django 4.2.7 on 2026-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamequestion_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Изменение баллов за лабу'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='score_for_lab',
            field=models.IntegerField(default=0, verbose_name='Баллы за лабу'),
        ),
    ]
